{
 "title": "App Suite / Core-Spellcheck",
 "tags": [ "app-suite" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,30m,1h,6h,1d" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(DictionaryCount{service=~\".*spellcheck.*\"}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(DictionaryCount{namespace=\"$namespace\",service=~\".*spellcheck.*\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(DictionaryCount{namespace=\"$namespace\",service=~\"$service\"}, pod)"
    }
   },
   {
    "name": "spellchecker",
    "label": "Spellchecker",
    "query": {
     "query": "ServerStatus{pod=~\"spellcheck.*\",property=\"serverStarts\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Spellchecker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Timeouts and SLA (<2s) [[pod]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ServerStatus{property=\"requestTimeout\"}[1m])",
     "legendFormat": "Timeouts {{instance}}"
    },
    {
     "expr": "increase(RequestTime_bucket{method=\"check-paragraph-spelling\",le=\"2\",pod=~\"$pod\"}[1m])  / on (pod) increase(RequestCount{method=\"check-paragraph-spelling\",statusCode=\"200\",pod=~\"$pod\"}[1m])",
     "legendFormat": "SLA {{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Methods (success only) [[pod]]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(RequestCount{pod=~\"$pod\",statusCode=\"200\"}[1m]) ",
       "legendFormat": "{{method}} {{pod}}"
      }
     ]
    },
    {
     "title": "Service Level [[pod]]",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(ServerStatus{pod=~\"$pod\",property=\"requestTimeout\"}[1m])",
       "legendFormat": "Timeouts {{instance}}"
      },
      {
       "expr": "increase(RequestTime_bucket{method=\"check-paragraph-spelling\",le=\"2\",pod=~\"$pod\"}[1m])",
       "legendFormat": "Reqs in 2s bucket {{pod}}"
      },
      {
       "expr": "increase(RequestCount{method=\"check-paragraph-spelling\",statusCode=\"200\",pod=~\"$pod\"}[1m])",
       "legendFormat": "Reqs {{pod}}"
      },
      { "legendFormat": "Ratio {{instance}}" }
     ]
    },
    {
     "title": "Methods (errors only) [[pod]]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(ServerStatus{pod=~\"$pod\",property=\"serverStarts\"}[1m])",
       "legendFormat": "Starts {{pod}}"
      },
      {
       "expr": "rate(RequestCount{pod=~\"$pod\",statusCode=\"error\"}[1m])",
       "legendFormat": "{{method}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "CacheStatus{property=\"currentCount\",type=\"suggestions\"} /  ignoring(property) CacheStatus{property=\"maxCount\",type=\"suggestions\"} ",
       "legendFormat": "Fill level {{locale}}"
      },
      {
       "expr": "Cache{scope=\"hit\",type=\"suggestions\"} /  ignoring(scope) Cache{scope=\"accessed\",type=\"suggestions\"} ",
       "legendFormat": "Hit ratio {{locale}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dictionary Handling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dictionaries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "DictionaryCount{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-{{locale}}-{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loaded Dictionaries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Loaded Dicts [[pod]]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DictionaryCount{pod=~\"$pod\",status=\"loaded\"} - ignoring (status) DictionaryCount{pod=~\"$pod\",status=\"unloaded\"}",
     "legendFormat": "Loaded {{instance}}-{{locale}}"
    }
   ]
  },
  {
   "title": "Restarts [[pod]]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ThreadCount [[pod]]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ServerStatus{property=\"threadCount\",pod=~\"$pod\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Starts [[pod]]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ServerStatus{property=\"serverStarts\",pod=~\"$pod\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spellcheck Instances All",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "ServerStatus{property=\"dictionaryTimeout\"}"
    }
   ]
  }
 ]
}