apiVersion: v2
name: odoo
version: 1.0.0
type: application
dependencies:
  - name: odoo
    version: "28.2.10"
    repository: "file://charts/odoo"
  - name: kubeaid-addons
    version: 1.1.0
    repository: file://../kubeaid-addons
