apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-cacheservice.configmap" . }}
data:
{{ (tpl (.Files.Glob "config/cacheservice.properties").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "config/logback.xml").AsConfig . ) | indent 2 }}
