{{- if .Values.cacheService.mysql.keystore }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-cacheservice.keystore" . }}
binaryData:
  {{- if .Values.cacheService.mysql.keystore.clientCertificateKeyStore }}
  ox-sql-clientstore: {{ .Values.cacheService.mysql.keystore.clientCertificateKeyStore }}
  {{- end }}
  {{- if .Values.cacheService.mysql.keystore.trustCertificateKeyStore }}
  ox-sql-truststore: {{ .Values.cacheService.mysql.keystore.trustCertificateKeyStore }}
  {{- end }}
{{- end }}