apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup-exporter.fullname" . }}-config
  labels:
    {{- include "backup-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |-
    exporter:
      debug: {{ .Values.exporter.debug | default "false" | quote }}
      postgres:
        s3:
          accessKeyId: {{ .Values.exporter.postgres.s3.accessKeyId | quote }}
          secretAccessKey: {{ .Values.exporter.postgres.s3.secretAccessKey | quote }}
        wal:
          {{- with .Values.exporter.postgres.wal.s3Region }}
          s3Region: {{ . | quote }}
          {{- end }}
      velero:
