networkpolicies: false
schedule:
  daily: true
  weekly: false
  sixhourly: false
  dailyTTL: 720h
  weeklyTTL: 2160h
  excludedResources:
    - workloadconfigurationscansummaries.spdx.softwarecomposition.kubescape.io
skipVolumePolicies:
  - app: rabbitmq
  - redis_setup_type: cluster
  - redis_setup_type: standalone
  - app: mongodb-replica-set-svc
  - app.kubernetes.io/name: opensearch
  - app.kubernetes.io/managed-by: cloudnative-pg
velero:
  revisionHistoryLimit: "0"
  configuration:
    logLevel: info
    features: EnableCSI
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 3m
      memory: 2Gi
  upgradeJobResources:
    requests:
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 300Mi
  kubectl:
    image:
      repository: docker.io/bitnamilegacy/kubectl
      tag: 1.33.4
