networkpolicies: false
schedule:
  daily: true
  weekly: false
  sixhourly: false
velero:
  revisionHistoryLimit: "0"
  configuration:
    logLevel: info
    features: EnableCSI
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 3m
      memory: 128Mi
  upgradeJobResources:
    requests:
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 300Mi
