{
 "title": "App Suite / Core-Cacheservice",
 "tags": [
  "java",
  "app-suite"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,30m,1h,6h,1d" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(process_uptime_seconds{service=~\".*cacheservice.*\"}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\",service=~\".*cacheservice.*\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_uptime_seconds{namespace=\"$namespace\",service=~\"$service\"}, pod)"
    }
   },
   {
    "name": "oc_group",
    "query": {
     "query": "label_values(cacheservice_items_maximum_count{namespace=\"$namespace\",service=~\"$service\"}, group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "non functional",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "text",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "options": {
      "content": "# ToDo\nHitRatio <br>\nMedian Duration Requests <br>\nHikariPool\nhttp... vs. cacheservice_request_count\n\nkommen die metrics erst später nach start ? \nobjectcache_size_...\nobjectcache_request_medianduration\nrequestcount per group\noldestmodification\nobjectcache_items_maximum\nobjectcache_items_current\n\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
     }
    },
    {
     "title": "Up (services in [[namespace]])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "up{namespace=~\"$namespace\"}\r\n",
       "legendFormat": "{{service}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "http metrics (not ready)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests  ([[pod]])",
     "type": "graph",
     "description": "Total Requests per second",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{outcome=\"SUCCESS\",pod=~\"$pod\"}[$interval]))",
       "legendFormat": "Success {{pod}}"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{outcome!=\"SUCCESS\",pod=~\"$pod\"}[$interval]))",
       "legendFormat": "Fail {{pod}}"
      }
     ]
    },
    {
     "title": "http ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(http_server_requests_seconds_sum{method=\"GET\",outcome=\"SUCCESS\",uri=\"/cache/getObjects/{group}/{key}\",}[$interval])",
       "legendFormat": "req sec sum {{uri}} {{pod}} "
      },
      {
       "expr": "http_server_requests_seconds_max{method=\"GET\",outcome=\"SUCCESS\",uri=\"/cache/getObjects/{group}/{key}\"}",
       "legendFormat": "req sec max {{uri}} {{pod}}"
      },
      {
       "expr": "rate(http_server_requests_seconds_count{method=\"GET\",outcome=\"SUCCESS\",uri=\"/cache/getObjects/{group}/{key}\"}[$interval])",
       "legendFormat": "req sec count {{uri}} {{pod}}"
      }
     ]
    },
    {
     "title": "Req Max ([[pod]])",
     "type": "graph",
     "description": "Total Requests per second",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{uri}}"
      }
     ]
    }
   ]
  },
  { "title": "CS Overview ( $service $pod )", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CSs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{namespace=~\"$namespace\",service=~\"$service\"}\r\n",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime ([[pod]])",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{service=~\"$service\",pod=~\"[[pod]]\"}",
     "legendFormat": "{{service}}"
    },
    {}
   ]
  },
  {
   "title": "Cache Hits ([[pod]])",
   "type": "gauge",
   "description": "red < 80%",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imageconverter_cache_hit_ratio{pod=~\"[[pod]]\"} ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Age Oldest Entry ([[pod]])",
   "type": "stat",
   "description": "yellow > 1h ; green > 1d",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cacheservice_oldest_modification_ms{group=\"$oc_group\",pod=~\"$pod\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Median  Duration ($pod)",
   "type": "stat",
   "description": "median for request types ",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cacheservice_request_medianduration_ms_total{pod=~\"$pod\",group!=\"admin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CS Requests ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Median Duration Total ([[oc_group]]  [[pod]])",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cacheservice_request_medianduration_ms_total{pod=~\"$pod\", group=~\"($oc_group|admin)\"}",
       "legendFormat": "{{group}} {{pod}} "
      }
     ]
    },
    {
     "title": "Requests Total ([[oc_group]] [[pod]])",
     "type": "graph",
     "description": "Total Requests per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cacheservice_request_count_total{group=~\"($oc_group|admin)\",pod=~\"$pod\"}[1m])",
       "legendFormat": "{{group}} {{pod}} "
      }
     ]
    },
    {
     "title": "Median Duration per type ([[oc_group]]  [[pod]])",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "cacheservice_request_medianduration_ms{pod=~\"$pod\",group=~\"($oc_group|admin)\"}",
       "legendFormat": "{{request}} {{group}} {{pod}}"
      }
     ]
    },
    {
     "title": "Requests per type ([[oc_group]] [[pod]])",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cacheservice_request_count{group=~\"($oc_group|admin)\",pod=\"$pod\"}[1m])",
       "legendFormat": "{{request}} {{group}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CS Objects ([[service]] [[pod]] [[oc_group]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Item Count ([[oc_group]]  [[pod]])",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "cacheservice_items_current_count{pod=~\"$pod\",group=~\"$oc_group\"}",
       "legendFormat": "Keys {{group}} {{pod}}"
      }
     ]
    },
    {
     "title": "Size ([[oc_group]] [[pod]])",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "cacheservice_size_current_bytes{pod=~\"$pod\", group=~\"$oc_group\"}",
       "legendFormat": "Size {{group}} {{pod}}"
      }
     ]
    },
    {
     "title": "Max Size ($pod $oc_group)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cacheservice_items_maximum_count{group=~\"$oc_group\"}",
       "legendFormat": "{{service}} {{pod}} {{group}} "
      }
     ]
    },
    {
     "title": "Max Bytes ($pod $oc_group)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 11, "x": 12, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cacheservice_size_maximum_bytes{group=~\"$oc_group\"}",
       "legendFormat": "{{service}} {{pod}} {{group}} "
      }
     ]
    },
    {
     "title": "Age Oldest Cache Entry ([[pod]] [[oc_group]])",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "cacheservice_oldest_modification_ms{group=~\"$oc_group\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{group}} {{request}}"
      }
     ]
    }
   ]
  }
 ]
}