{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.fluentbit
  namespace: logging
spec:
  order: 100
  selector:
    app.kubernetes.io/name == 'fluent-bit'
  types:
  - Egress
  egress:
  # Graylog GELF output
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 5555
  # DNS UDP 
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53
      namespaceSelector: projectcalico.org/name == 'kube-system'
      selector: k8s-app == 'kube-dns'
  # DNS TCP 
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 53
      namespaceSelector: projectcalico.org/name == 'kube-system'
      selector: k8s-app == 'kube-dns'
  # Kubernetes API server (kubernetes.default.svc.cluster.local:443) for filters
  - action: Allow
    protocol: TCP
    destination:
      services:
        name: kubernetes
        namespace: default
  # Allow access to EC2 metadata endpoint
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 443
      nets:
      - 169.254.169.254/32
{{ end }}
