{{- if .Values.backupExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeaid-agent.backupExporter.fullname" . }}
  labels:
    {{- include "kubeaid-agent.backupExporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backupExporter.autoscaling.enabled }}
  replicas: {{ .Values.backupExporter.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubeaid-agent.backupExporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.backupExporter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubeaid-agent.backupExporter.labels" . | nindent 8 }}
        {{- with .Values.backupExporter.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.backupExporter.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubeaid-agent.backupExporter.serviceAccountName" . }}
      {{- with .Values.backupExporter.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.backupExporter.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.backupExporter.image.repository }}:{{ .Values.backupExporter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backupExporter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backupExporter.service.port }}
              protocol: TCP
          env:
            - name: POSTGRES_EXPORTER_MAX_RPO
              value: {{ .Values.backupExporter.exporter.postgres.max_rpo | default "26h" | quote }}
            - name: POSTGRES_EXPORTER_INTERVAL_RATE
              value: {{ .Values.backupExporter.exporter.postgres.interval_rate | default "0.25" | quote }}
            - name: VELERO_EXPORTER_MAX_RPO
              value: {{ .Values.backupExporter.exporter.velero.max_rpo | default "26h" | quote }}
            - name: VELERO_EXPORTER_INTERVAL_RATE
              value: {{ .Values.backupExporter.exporter.velero.interval_rate | default "0.25" | quote }}
            {{- with .Values.backupExporter.exporter.velero.s3.url }}
            - name: VELERO_S3_ENDPOINT
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.backupExporter.exporter.velero.s3.prefix }}
            - name: VELERO_S3_PREFIX
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.backupExporter.exporter.velero.s3.secretName }}
            - name: VELERO_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: access-key-id
            - name: VELERO_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: secret-access-key
            - name: VELERO_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: region
            - name: VELERO_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: bucket
            {{- else }}
            {{- with .Values.backupExporter.exporter.velero.s3.accessKeyId }}
            - name: VELERO_S3_ACCESS_KEY_ID
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.backupExporter.exporter.velero.s3.secretAccessKey }}
            - name: VELERO_S3_SECRET_ACCESS_KEY
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.backupExporter.exporter.velero.s3.region }}
            - name: VELERO_S3_REGION
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.backupExporter.exporter.velero.s3.bucket }}
            - name: VELERO_S3_BUCKET
              value: {{ . | quote }}
            {{- end }}
            {{- end }}
            {{- if (.Values.backupExporter.exporter.mongodb).enabled }}
            - name: MONGODB_BACKUP_ENABLED
              value: "true"
            - name: MONGODB_EXPORTER_MAX_RPO
              value: {{ .Values.backupExporter.exporter.mongodb.max_rpo | default "26h" | quote }}
            - name: MONGODB_EXPORTER_INTERVAL_RATE
              value: {{ .Values.backupExporter.exporter.mongodb.interval_rate | default "0.25" | quote }}
            {{- with .Values.backupExporter.exporter.mongodb.s3.secretName }}
            - name: MONGODB_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: access-key-id
            - name: MONGODB_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: secret-access-key
            {{- else }}
            {{- with .Values.backupExporter.exporter.mongodb.s3.accessKeyId }}
            - name: MONGODB_S3_ACCESS_KEY_ID
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.backupExporter.exporter.mongodb.s3.secretAccessKey }}
            - name: MONGODB_S3_SECRET_ACCESS_KEY
              value: {{ . | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if (.Values.backupExporter.exporter.sealedSecrets).enabled }}
            - name: SEALED_SECRETS_BACKUP_ENABLED
              value: "true"
            - name: SEALED_SECRETS_EXPORTER_MAX_RPO
              value: {{ .Values.backupExporter.exporter.sealedSecrets.max_rpo | default "26h" | quote }}
            - name: SEALED_SECRETS_EXPORTER_INTERVAL_RATE
              value: {{ .Values.backupExporter.exporter.sealedSecrets.interval_rate | default "0.25" | quote }}
            {{- with .Values.backupExporter.exporter.sealedSecrets.s3.bucket }}
            - name: SEALED_SECRETS_S3_BUCKET
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.backupExporter.exporter.sealedSecrets.s3.endpoint }}
            - name: SEALED_SECRETS_S3_ENDPOINT
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.backupExporter.exporter.sealedSecrets.s3.secretName }}
            - name: SEALED_SECRETS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: access-key-id
            - name: SEALED_SECRETS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: secret-access-key
            {{- else }}
            {{- with .Values.backupExporter.exporter.sealedSecrets.s3.accessKeyId }}
            - name: SEALED_SECRETS_S3_ACCESS_KEY_ID
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.backupExporter.exporter.sealedSecrets.s3.secretAccessKey }}
            - name: SEALED_SECRETS_S3_SECRET_ACCESS_KEY
              value: {{ . | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- $s3 := .Values.backupExporter.exporter.postgres.s3 }}
            {{- with $s3.secretName }}
            - name: POSTGRES_S3_LOGICAL_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: access-key-id
            - name: POSTGRES_S3_LOGICAL_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: secret-access-key
            - name: POSTGRES_S3_WAL_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: access-key-id
            - name: POSTGRES_S3_WAL_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: secret-access-key
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /utils/config
              readOnly: true
            {{- with .Values.backupExporter.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.backupExporter.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backupExporter.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backupExporter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- with .Values.backupExporter.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: config
          configMap:
            name: {{ include "kubeaid-agent.backupExporter.fullname" . }}-config
            items:
              - key: config.yaml
                path: config.yaml
      {{- with .Values.backupExporter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backupExporter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backupExporter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
