{{- if .Values.securityExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeaid-agent.securityExporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeaid-agent.securityExporter.labels" . | nindent 4 }}
    {{- with .Values.securityExporter.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.securityExporter.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "kubeaid-agent.securityExporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.securityExporter.service.port }}
      targetPort: http
{{- end }}
