---
version: 2

before:
  hooks:
    - bash bin/helm-repo-update.sh

changelog:
  use: github
  sort: asc
  format: "[{{ .SHA }}](https://github.com/obmondo/kubeaid/commit/{{ .SHA }}) {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  abbrev: 7
  filters:
    exclude:
      - init
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  # Group commits messages by given regex and title.
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Docs
      regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Major Version Upgrades'
      regexp: '^.*### Major Version Upgrades.*$'
      order: 3
    - title: 'Minor Version Upgrades'
      regexp: '^.*### Minor Version Upgrades.*$'
      order: 4
    - title: 'Patch Version Upgrades'
      regexp: '^.*### Patch Version Upgrades.*$'
      order: 5
    - title: Others
      order: 999

builds:
  - skip: true

release:
  github:
    owner: ashish
    name: kubeaid
  prerelease: auto
  make_latest: true
  header: |
    ## Release {{ .Tag }}

    This release includes automated Helm chart updates.
  footer: |
    **Full Changelog**: https://github.com/obmondo/kubeaid/compare/{{ .PreviousTag }}...{{ .Tag }}
