apiVersion: v2
name: calcom
version: 1.0.0
dependencies:
  - name: calcom
    version: 0.8.6
    repository: https://obmondo.github.io/calcom-helm

  - name: kubeaid-addons
    version: 1.1.0
    repository: file://../kubeaid-addons
