apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: {{ .Values.global.clusterName }}
  labels:
    cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
spec:
  region: {{ .Values.aws.region }}
  sshKeyName: {{ .Values.aws.sshKeyName }}
