{{- if (.Values.workerNodes).autoScaler }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ .Values.global.clusterName }}-mp-0
spec:
  clusterName: {{ .Values.global.clusterName }}
  replicas: {{ .Values.workerNodes.replicas }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Values.global.clusterName }}
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ .Values.global.clusterName }}
      clusterName: {{ .Values.global.clusterName }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachinePool
        name: {{ .Values.global.clusterName }}-mp-0
      version: {{ .Values.global.kubernetes.version }}
{{- end }}
