{{- if (not (.Values.global.capa).autoScaler) }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ .Values.global.clusterName }}-md-0
spec:
  clusterName: {{ .Values.global.clusterName }}
  replicas: {{ .Values.workerNodes.replicas }}
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ .Values.global.clusterName }}
      clusterName: {{ .Values.global.clusterName }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachineTemplate
        name: {{ .Values.global.clusterName }}-md-0
      version: {{ .Values.global.kubernetes.version }}
{{- end }}
