harborProxyCache:
  enabled: false

resourceQuotaLimitRangeGenerator:
  enabled: true

  defaults:
    resourceQuota:
      pods: "100"

      cpu:
        request: "100"

      memory:
        request: 200Gi
        limit: 400Gi

      storage:
        persistentVolumeClaims:
        request:

      ephemeralStorage:
        request:
        limit:

    limitRange:
      container:
        cpu:
          defaultRequest: 100m

        memory:
          defaultRequest: 128Mi
          default: 256Mi
          max: 4Gi

      pod:
        memory:
          max: 16Gi

      pvc:
        storage:
          max: 100Gi

  overrides:
    rook-ceph:
      limitRange:
        container: {}
