whoami:
  lables:
    traefik.http.routers.whoami.middlewares: traefik-forward-auth

  ingress:
    enabled: true

  image:
    tag: v1.12.0

global:
  netpol:
    enabled: false
  whoami:
    netpol: false
postgresql:
  monitoring:
    enablePodMonitor: true
