apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-extra-config
  labels:
{{ include "labels" . | nindent 4}}
data:
  turnserver.conf: |-
  {{- with tpl .Values.coturn.extraTurnserverConfiguration . }}
  {{- . | trim | nindent 4 }}
  {{- end }}
  {{- range .Values.coturn.extraDeniedPeerIPs }}
  {{- printf "denied-peer-ip=%s" . | nindent 4 }}
  {{- end }}
