{{/*
If the user has enabled the postgresql subchart or passed in an external
Database with plain text credentials, we create a secret with those credentials
to
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
{{ include "labels" . | nindent 4}}
data:
  {{/* if cnpg is enabled */}}
  {{- if .Values.cnpg.enabled }}
  hostname: {{ template "cluster.fullname" .Subcharts.cnpg }}
  database: {{ .Values.cnpg.cluster.initdb.database | b64enc | quote }}
  username: {{ .Values.cnpg.cluster.initdb.owner | b64enc | quote }}
  password: {{ randAlphaNum 24 | b64enc | quote }}

  {{/* if pxc mysql is enabled */}}
  {{- else if .Values.mysql.enabled }}
  hostname: {{ template "pxc-database.fullname" .Subcharts.mysql }}
  {{- with (first .Values.mysql.users) }}
  {{- with (first .dbs) }}
  database: {{ . | b64enc | quote }}
  {{- end }}
  username: {{ .name | b64enc | quote }}
  {{- end }}
  password: {{ randAlphaNum 24 | b64enc | quote }}

  {{/* if external database is enabled */}}
  {{- else if .Values.externalDatabase.enabled }}
  hostname: {{ .Values.externalDatabase.hostname | b64enc | quote }}
  database: {{ .Values.externalDatabase.database | b64enc | quote }}
  username: {{ .Values.externalDatabase.username | b64enc | quote }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
