name: kubeaid

"on":
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  kubeaid:
    name: KubeAid CI
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.HARBOR_REGISTRY }}/${{ vars.KUBEAID_CI_IMAGE }}:${{ vars.KUBEAID_CI_TAG }}
      credentials:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: shellcheck
      run: |
        find . -type f \( -name *.sh -o -name '*.bash' \) ! \( -path './argocd-helm-charts/*/charts/*' -o -path './build/vendor/*' -o -path './build/kube-prometheus/libraries/*' \) | xargs shellcheck

    - name: yamllint
      run: |
        find . -type f -name '*.yaml' \
          ! -path './argocd-helm-charts/**/templates/*' \
          ! -path './argocd-helm-charts/**/examples/*.yaml' \
          -exec yamllint --strict --config-file .yamllint {} +

    - name: opa
      run: |
        opa test ./argocd-helm-charts/gatekeeper/policies -v

    - name: jsonnetlint
      run: ./bin/lint-jsonnetfmt.sh
