apiVersion: v2
name: collabora-online
description: Collabora Online - collaborative office suite rendering documents for a WOPI host.
type: application
version: 1.0.0
# see latest chart here: https://artifacthub.io/packages/helm/collabora-online/collabora-online
dependencies:
  - name: collabora-online
    version: 1.3.5
    repository: https://collaboraonline.github.io/online/
