{{- if .Values.postgresql.backups.enabled }}

{{- $backups := .Values.postgresql.backups }}

{{/* NOTE : While it is technically possible to reuse the same ObjectStore for multiple Cluster
            resources within the same namespace, it is strongly recommended to dedicate one object
            store per PostgreSQL cluster to ensure data isolation and operational clarity. */}}

apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: keycloak-pgsql-backups

spec:
  configuration:
    {{- if $backups.endpointURL }}
    endpointURL: {{ $backups.endpointURL }}
    {{- end }}
    destinationPath: {{ required ".destinationPath must be provided" $backups.destinationPath }}

    {{- if eq $backups.provider "aws" }}
    s3Credentials:
      {{- if $backups.aws.enableKube2IAMIntegration }}
      inheritFromIAMRole: true
      {{- else }}
      accessKeyId:
        name: keycloak-pgsql-backup-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: keycloak-pgsql-backup-creds
        key: ACCESS_SECRET_KEY
    {{- end }}

    {{- else if eq $backups.provider "azure" }}
    azureCredentials:
      connectionString:
        name: keycloak-pgsql-backup-creds
        key: AZURE_CONNECTION_STRING
    {{- end }}

    wal:
      compression: gzip
      encryption: AES256
      maxParallel: 8

  retentionPolicy: {{ $backups.retentionPolicy }}
{{- end }}
