apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obmondo-backup-exporter.fullname" . }}-config
  labels:
    {{- include "obmondo-backup-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |-
    exporter:
      debug: {{ .Values.exporter.debug | default "false" | quote }}
      postgres:
        logical:
          {{- $logical := .Values.exporter.postgres.logical.ignore_clusters | default dict }}
          ignore_clusters:
          {{- range $ns, $clusterList := $logical }}
            {{ $ns }}:
            {{- range $clusterList }}
              - {{ . }}
            {{- end }}
          {{- end }}
          s3:
            accessKeyId: {{ .Values.exporter.postgres.logical.s3.accessKeyId | quote }}
            secretAccessKey: {{ .Values.exporter.postgres.logical.s3.secretAccessKey | quote }}
        wal:
          {{- $wal := .Values.exporter.postgres.wal.ignore_clusters | default dict }}
          ignore_clusters:
          {{- range $ns, $clusterList := $wal }}
            {{ $ns }}:
            {{- range $clusterList }}
              - {{ . }}
            {{- end }}
          {{- end }}
          s3:
            accessKeyId: {{ .Values.exporter.postgres.wal.s3.accessKeyId | quote }}
            secretAccessKey: {{ .Values.exporter.postgres.wal.s3.secretAccessKey | quote }}
      velero:
        {{- $ignoreNamespaces := .Values.exporter.velero.ignore_namespaces | default list }}
        ignore_namespaces:
        {{- range $ignoreNamespaces }}
          - {{ . | quote }}
        {{- end }}
