apiVersion: v2
appVersion: v1.18.0-0.0.8
description: Helm Chart for Hcloud Cloud Controller Manager
home: https://github.com/syself/charts/tree/main/charts/ccm-hetzner
maintainers:
- email: info@syself.com
  name: Syself
  url: https://github.com/syself
name: ccm-hetzner
type: application
version: 1.1.15
