apiVersion: v1
kind: Service
metadata:
  name: {{ include "ox-common.names.fullname" . }}
  labels:
    {{- include "ox-common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8003
      protocol: TCP
      name: http
    - port: {{ .Values.service.portMetrics }}
      targetPort: 8002
      protocol: TCP
      name: httpmetrics
  selector:
    {{- include "ox-common.labels.matchLabels" . | nindent 4 }}
