apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
spec:
  destination:
    namespace: rustfs
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-helm-charts/rustfs
    repoURL: https://github.com/YourOrg/kubeaid.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
