annotations:
  artifacthub.io/category: networking
  artifacthub.io/changes: |
    - Update base image to HAProxy 3.3.10
  artifacthub.io/images: |
    - name: haproxy
      image: docker.io/haproxytech/haproxy-alpine:3.3.6
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/haproxytech/helm-charts/issues
apiVersion: v2
appVersion: 3.3.10
description: A Helm chart for HAProxy on Kubernetes
home: https://github.com/haproxytech/helm-charts/tree/main/haproxy
icon: https://raw.githubusercontent.com/haproxytech/helm-charts/main/haproxy/chart-icon.png
keywords:
- haproxy
kubeVersion: '>=1.17.0-0'
maintainers:
- email: dkorunic@haproxy.com
  name: Dinko Korunic
name: haproxy
sources:
- http://www.haproxy.org/
type: application
version: 1.29.0
