{{- if .Values.vulsServer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vuls-dictionary.fullname" . }}-vuls-config
  labels:
    {{- include "vuls-dictionary.labels" . | nindent 4 }}
data:
  config.toml: |
    [vuls2]
    Path = {{ .Values.vuls2.dbPath | quote }}
    SkipUpdate = true
{{- end }}
