{{- if .Values.g10k.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "puppetserver.name" . }}-g10k
spec:
  suspend: false
  schedule: {{ .Values.g10k.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            {{- toYaml .Values.g10k.podSecurityContext | nindent 12 }}
            runAsUser: {{ .Values.puppetserver.global.securityContext.runAsUser }}
            runAsGroup: {{ .Values.puppetserver.global.securityContext.runAsGroup }}
            fsGroup: {{ .Values.puppetserver.global.securityContext.fsGroup }}
            fsGroupChangePolicy: "OnRootMismatch"
          volumes:
            - name: puppet-code-storage
              persistentVolumeClaim:
                claimName: {{ template "puppetserver.name" . }}-code-claim
            - name: g10k-config-volume
              configMap:
                name: {{ include "puppetserver.name" . }}-g10k-config
            {{- if or (.Values.g10k.code.viaSsh.credentials.existingSecret) (and (.Values.g10k.code.viaSsh.credentials.ssh.value) (.Values.g10k.code.viaSsh.credentials.known_hosts.value)) }}
            - name: g10k-code-ssh
              secret:
                secretName: {{ .Values.g10k.code.viaSsh.credentials.existingSecret }}
                defaultMode: 288 # = mode 0440
                items:
                  - key: id_rsa
                    path: id_rsa
                  - key: known_hosts
                    path: known_hosts
            {{- end }}
            {{- if or (.Values.g10k.hiera.viaSsh.credentials.existingSecret) (and (.Values.g10k.hiera.viaSsh.credentials.ssh.value) (.Values.g10k.hiera.viaSsh.credentials.known_hosts.value)) }}
            - name: g10k-hiera-ssh
              secret:
                secretName: {{ .Values.g10k.hiera.viaSsh.credentials.existingSecret }}
                defaultMode: 288 # = mode 0440
                items:
                  - key: id_rsa
                    path: id_rsa
                  - key: known_hosts
                    path: known_hosts
            {{- end }}
          restartPolicy: OnFailure
          containers:
            - name: g10k-code
              securityContext:
                {{- toYaml .Values.g10k.securityContext | nindent 16 }}
              image: "{{ .Values.g10k.image.repository }}:{{ .Values.g10k.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.g10k.image.pullPolicy }}
              args:
                - set -e
                - mkdir -p /tmp/linuxaid
                - /usr/local/bin/g10k -verbose -clonegit -tags -config /etc/puppetlabs/puppet/g10k_code.yaml
                - /usr/bin/rsync -avc --delete /tmp/linuxaid {{ .Values.puppetserver.puppetserver.puppetbasedir }}
              resources:
                {{- toYaml .Values.g10k.resources | nindent 16 }}
              volumeMounts:
                - name: puppet-code-storage
                  mountPath: /etc/puppetlabs/code/
                - name: g10k-config-volume
                  mountPath: /etc/puppetlabs/puppet/g10k_code.yaml
                  subPath: g10k_code.yaml
                {{- with .Values.g10k.code.viaSsh.credentials }}
                {{- if or (.existingSecret) (and (.ssh.value) (.known_hosts.value)) }}
                - name: g10k-code-ssh
                  mountPath: /home/puppet/.ssh
                {{- end }}
                {{- end }}
            - name: g10k-hiera
              securityContext:
                {{- toYaml .Values.g10k.securityContext | nindent 16 }}
              image: "{{ .Values.g10k.image.repository }}:{{ .Values.g10k.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.g10k.image.pullPolicy }}
              args:
                - set -e
                - mkdir -p /tmp/linuxaid-config
                - /usr/local/bin/g10k -verbose -clonegit -tags -config /etc/puppetlabs/puppet/g10k_hiera.yaml
                - /usr/bin/rsync -avc --delete /tmp/linuxaid-config /etc/puppetlabs/code/hiera-data
              resources:
                {{- toYaml .Values.g10k.resources | nindent 16 }}
              volumeMounts:
                - name: puppet-code-storage
                  mountPath: /etc/puppetlabs/code/
                - name: g10k-config-volume
                  mountPath: /etc/puppetlabs/puppet/g10k_hiera.yaml
                  subPath: g10k_hiera.yaml
                {{- with .Values.g10k.hiera.viaSsh.credentials }}
                {{- if or (.existingSecret) (and (.ssh.value) (.known_hosts.value)) }}
                - name: g10k-hiera-ssh
                  mountPath: /home/puppet/.ssh
                {{- end }}
                {{- end }}
{{- end }}
