{{- if .Values.global.postgresql.enabled }}
{{- $postgresql := .Values.global.postgresql }}

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.global.postgresql.instanceName }}-pgsql
  {{- with $postgresql.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  instances: {{ $postgresql.instances }}

  inheritedMetadata:
    labels:
      velero.io/exclude-from-backup: "true"

  {{- $resources := deepCopy $postgresql.resources }}
  {{- range $resourceType, $resourceValues := $resources }}
    {{- range $resourceName, $resourceValue := $resourceValues }}
      {{- if eq $resourceValue nil }}
        {{- $_ := unset $resourceValues $resourceName }}
      {{- end }}
    {{- end }}
    {{- if not $resourceValues }}
      {{- $_ := unset $resources $resourceType }}
    {{- end }}
  {{- end }}
  {{- if $postgresql.disableCpuLimit }}
    {{- with $resources.limits }}
      {{- $_ := unset . "cpu" }}
    {{- end }}
    {{- if not $resources.limits }}
      {{- $_ := unset $resources "limits" }}
    {{- end }}
  {{- end }}
  {{- with $resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  storage:
    size: {{ $postgresql.size }}
    {{- if $postgresql.storageClass }}
    storageClass: {{ $postgresql.storageClass }}
    {{- end }}

  {{- if $postgresql.backups.enabled }}
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ .Values.global.postgresql.instanceName }}-pgsql-backups
        serverName: "revision-{{ $postgresql.revision }}"
  {{- end }}

  bootstrap:
    {{- if $postgresql.recover.enabled }}
    recovery:
      source: {{ .Values.global.postgresql.instanceName }}-pgsql
    {{- else }}
    initdb:
      database: {{ .Values.global.postgresql.instanceName }}
      owner: {{ .Values.global.postgresql.instanceName }}
    {{- end }}

  {{- if $postgresql.recover.enabled }}
  externalClusters:
    - name: {{ .Values.global.postgresql.instanceName }}-pgsql
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: {{ .Values.global.postgresql.instanceName }}-pgsql-backups
          serverName: "revision-{{ $postgresql.recover.revision }}"
  {{- end }}

  # Latest Official CNPG docs recommends disabling below setting within kind: Cluster resource and using a Kind: PodMonitor resource separately
  # Ref - https://cloudnative-pg.io/docs/1.29/monitoring/#deprecation-of-automatic-podmonitor-creation
  monitoring:
    enablePodMonitor: false
{{- end }}
