apiVersion: v2
name: netbird-operator
description: NetBird Kubernetes Operator
type: application
version: 0.2.0
dependencies:
  - name: netbird-operator
    repository: oci://ghcr.io/netbirdio/helm-charts
    version: 0.7.0
