apiVersion: v2
name: goalerts
description: GoAlert - open source on-call scheduling, automated escalations and notifications.
type: application
version: 1.0.0
appVersion: v0.32.0
home: https://github.com/target/goalert
sources:
  - https://github.com/target/goalert
keywords:
  - on-call
  - scheduling
  - escalations
  - notifications
  - alerting
  - incident-response
