{{- if (.Values.postgres.logicalbackup).enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-logical-backup
spec:
  concurrencyPolicy: Forbid
  suspend: false
  schedule: {{ (.Values.postgres.logicalbackup).schedule | default "30 00 * * *" | quote }}
  successfulJobsHistoryLimit: {{ (.Values.postgres.logicalbackup).successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ (.Values.postgres.logicalbackup).failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: logical-backup
              image: ghcr.io/obmondo/postgres-logical-backup:3.1.7
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  memory: 500Mi
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: PGHOST
                  value: {{ .Values.postgres.host | default "odoo-pgsql-rw" | quote }}
                - name: PGPORT
                  value: {{ .Values.postgres.port | default 5432 | quote }}
                - name: PGUSER
                  value: {{ .Values.postgres.user | default "odoo" | quote }}
                - name: PGDATABASE
                  value: {{ .Values.postgres.db | default "odoo" | quote }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: odoo-pgsql-app
                      key: password
                - name: CLUSTER_NAME_LABEL
                  value: {{ (.Values.postgres.logicalbackup).pgOperatorClusterName | default "odoo-pgsql" | quote }}
            {{- if eq (.Values.postgres.logicalbackup).provider "s3" }}
                - name: LOGICAL_BACKUP_PROVIDER
                  value: "s3"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ (.Values.postgres.logicalbackup).secretName | default "odoo-pgsql-postgres-pod-env" | quote }}
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ (.Values.postgres.logicalbackup).secretName | default "odoo-pgsql-postgres-pod-env" | quote }}
                      key: AWS_SECRET_ACCESS_KEY
                - name: LOGICAL_BACKUP_S3_ENDPOINT
                  value: {{ (.Values.postgres.logicalbackup).s3endpoint | quote }}
                - name: LOGICAL_BACKUP_S3_BUCKET
                  value: {{ (.Values.postgres.logicalbackup).s3bucket | quote }}
                - name: LOGICAL_BACKUP_S3_BUCKET_SCOPE_SUFFIX
                  value: {{ (.Values.postgres.logicalbackup).s3bucketscopesuffix | default "logicalbackup" | quote }}
                - name: LOGICAL_BACKUP_S3_REGION
                  value: {{ (.Values.postgres.logicalbackup).s3region | default "us-east-1" | quote }}
                - name: LOGICAL_BACKUP_S3_RETENTION_TIME
                  value: {{ (.Values.postgres.logicalbackup).retention | default "30 days" | quote }}

              {{- else if eq .Values.postgres.logicalbackup.provider "az" }}
                - name: LOGICAL_BACKUP_PROVIDER
                  value: "az"
                - name: LOGICAL_BACKUP_AZURE_STORAGE_ACCOUNT_NAME
                  value: {{ (.Values.postgres.logicalbackup).storeageaccount }}
                - name: LOGICAL_BACKUP_AZURE_STORAGE_CONTAINER
                  value: {{ (.Values.postgres.logicalbackup).azurecontainer }}
                - name: LOGICAL_BACKUP_AZURE_STORAGE_ACCOUNT_KEY
                  valueFrom:
                    secretKeyRef:
                      key: LOGICAL_BACKUP_AZURE_STORAGE_ACCOUNT_KEY
                      name: odoo-pgsql-postgres-pod-env
                - name: LOGICAL_BACKUP_S3_BUCKET
                  value: {{ (.Values.postgres.logicalbackup).azurecontainer }}
                - name: LOGICAL_BACKUP_S3_BUCKET_SCOPE_SUFFIX
                  value: {{ (.Values.postgres.logicalbackup).s3bucketscopesuffix | default "logicalbackup" }}

            {{- end }}
                - name: PG_VERSION
                  value: {{ (.Values.postgres.logicalbackup).pgversion | default 18 | quote }}
                - name: POSTGRES_OPERATOR
                  value: {{ (.Values.postgres.logicalbackup).postgresOperator | default "cnpg" | quote }}
                - name: USE_PG_DUMP
                  value: "true"
              securityContext:
                allowPrivilegeEscalation: true
                privileged: false
                readOnlyRootFilesystem: false
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          terminationGracePeriodSeconds: 300
{{- end }}