{{- if (.Values.harborProxyCache).enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: harbor-imagepullsecrets-inject
  annotations:
    policies.kyverno.io/title: "Inject Harbor imagePullSecrets for proxy cache"
    policies.kyverno.io/category: "Image Registry"
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: "Pod,Deployment,StatefulSet,DaemonSet,Job,CronJob"
    policies.kyverno.io/description: >-
      Automatically injects Harbor imagePullSecrets to pods that pull images from Harbor proxy cache.
      This ensures authentication works for private/cached images.
    kyverno.io/kubernetes-version: "1.27+"
    policies.kyverno.io/minversion: "1.11.0"
spec:
  background: false
  mutateExistingOnPolicyUpdate: {{ .Values.harborProxyCache.mutateExistingOnPolicyUpdate | default true }}
  rules:
    - name: inject-harbor-secrets-pod
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
                - UPDATE
      mutate:
        foreach:
          - list: "request.object.spec.containers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: Equals
                  value: {{ .Values.harborProxyCache.registry | quote }}
            patchStrategicMerge:
              spec:
                imagePullSecrets:
                  - name: {{ .Values.harborProxyCache.imagePullSecretName | default "harbor-proxy-cache" }}
          - list: "request.object.spec.initContainers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: Equals
                  value: {{ .Values.harborProxyCache.registry | quote }}
            patchStrategicMerge:
              spec:
                imagePullSecrets:
                  - name: {{ .Values.harborProxyCache.imagePullSecretName | default "harbor-proxy-cache" }}
    - name: inject-harbor-secrets-workload
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Job
              operations:
                - CREATE
                - UPDATE
      mutate:
        foreach:
          - list: "request.object.spec.template.spec.containers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: Equals
                  value: {{ .Values.harborProxyCache.registry | quote }}
            patchStrategicMerge:
              spec:
                template:
                  spec:
                    imagePullSecrets:
                      - name: {{ .Values.harborProxyCache.imagePullSecretName | default "harbor-proxy-cache" }}
          - list: "request.object.spec.template.spec.initContainers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: Equals
                  value: {{ .Values.harborProxyCache.registry | quote }}
            patchStrategicMerge:
              spec:
                template:
                  spec:
                    imagePullSecrets:
                      - name: {{ .Values.harborProxyCache.imagePullSecretName | default "harbor-proxy-cache" }}
    - name: inject-harbor-secrets-cronjob
      match:
        any:
          - resources:
              kinds:
                - CronJob
              operations:
                - CREATE
                - UPDATE
      mutate:
        foreach:
          - list: "request.object.spec.jobTemplate.spec.template.spec.containers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: Equals
                  value: {{ .Values.harborProxyCache.registry | quote }}
            patchStrategicMerge:
              spec:
                jobTemplate:
                  spec:
                    template:
                      spec:
                        imagePullSecrets:
                          - name: {{ .Values.harborProxyCache.imagePullSecretName | default "harbor-proxy-cache" }}
          - list: "request.object.spec.jobTemplate.spec.template.spec.initContainers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: Equals
                  value: {{ .Values.harborProxyCache.registry | quote }}
            patchStrategicMerge:
              spec:
                jobTemplate:
                  spec:
                    template:
                      spec:
                        imagePullSecrets:
                          - name: {{ .Values.harborProxyCache.imagePullSecretName | default "harbor-proxy-cache" }}
{{- end }}

