{{- if (.Values.harborProxyCache).enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: harbor-proxy-cache-mutate
  annotations:
    policies.kyverno.io/title: "Redirect Docker Hub images to Harbor proxy cache"
    policies.kyverno.io/category: "Image Registry"
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: "Pod,Deployment,StatefulSet,DaemonSet,Job,CronJob"
    policies.kyverno.io/description: >-
      Automatically redirects docker.io and registry-1.docker.io images to Harbor proxy cache
      to bypass Docker Hub rate limits. This policy mutates container images at admission time.
    kyverno.io/kubernetes-version: "1.27"
    policies.kyverno.io/minversion: 1.11.4
spec:
  admission: true
  background: true
  emitWarning: false
  failurePolicy: Ignore
  mutateExistingOnPolicyUpdate: {{ .Values.harborProxyCache.mutateExistingOnPolicyUpdate | default false }}
  rules:
    - name: mutate-docker-io-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
                - UPDATE
      mutate:
        foreach:
          - list: "request.object.spec.containers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: AnyIn
                  value:
                    - "docker.io"
                    - "registry-1.docker.io"
            patchStrategicMerge:
              spec:
                containers:
                  - (name): "{{`{{ element.name }}`}}"
                    image: "{{ .Values.harborProxyCache.registry }}/{{ .Values.harborProxyCache.project }}/{{`{{ imageData.repository }}`}}:{{`{{ imageData.tag || 'latest' }}`}}"
          - list: "request.object.spec.initContainers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: AnyIn
                  value:
                    - "docker.io"
                    - "registry-1.docker.io"
            patchStrategicMerge:
              spec:
                initContainers:
                  - (name): "{{`{{ element.name }}`}}"
                    image: "{{ .Values.harborProxyCache.registry }}/{{ .Values.harborProxyCache.project }}/{{`{{ imageData.repository }}`}}:{{`{{ imageData.tag || 'latest' }}`}}"
    - name: mutate-docker-io-workload-containers
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Job
              operations:
                - CREATE
                - UPDATE
      mutate:
        foreach:
          - list: "request.object.spec.template.spec.containers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: AnyIn
                  value:
                    - "docker.io"
                    - "registry-1.docker.io"
            patchStrategicMerge:
              spec:
                template:
                  spec:
                    containers:
                      - (name): "{{`{{ element.name }}`}}"
                        image: "{{ .Values.harborProxyCache.registry }}/{{ .Values.harborProxyCache.project }}/{{`{{ imageData.repository }}`}}:{{`{{ imageData.tag || 'latest' }}`}}"
          - list: "request.object.spec.template.spec.initContainers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: AnyIn
                  value:
                    - "docker.io"
                    - "registry-1.docker.io"
            patchStrategicMerge:
              spec:
                template:
                  spec:
                    initContainers:
                      - (name): "{{`{{ element.name }}`}}"
                        image: "{{ .Values.harborProxyCache.registry }}/{{ .Values.harborProxyCache.project }}/{{`{{ imageData.repository }}`}}:{{`{{ imageData.tag || 'latest' }}`}}"
    - name: mutate-docker-io-cronjob-containers
      match:
        any:
          - resources:
              kinds:
                - CronJob
              operations:
                - CREATE
                - UPDATE
      mutate:
        foreach:
          - list: "request.object.spec.jobTemplate.spec.template.spec.containers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: AnyIn
                  value:
                    - "docker.io"
                    - "registry-1.docker.io"
            patchStrategicMerge:
              spec:
                jobTemplate:
                  spec:
                    template:
                      spec:
                        containers:
                          - (name): "{{`{{ element.name }}`}}"
                            image: "{{ .Values.harborProxyCache.registry }}/{{ .Values.harborProxyCache.project }}/{{`{{ imageData.repository }}`}}:{{`{{ imageData.tag || 'latest' }}`}}"
          - list: "request.object.spec.jobTemplate.spec.template.spec.initContainers[]"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{`{{ element.image }}`}}"
            preconditions:
              all:
                - key: "{{`{{ imageData.registry }}`}}"
                  operator: AnyIn
                  value:
                    - "docker.io"
                    - "registry-1.docker.io"
            patchStrategicMerge:
              spec:
                jobTemplate:
                  spec:
                    template:
                      spec:
                        initContainers:
                          - (name): "{{`{{ element.name }}`}}"
                            image: "{{ .Values.harborProxyCache.registry }}/{{ .Values.harborProxyCache.project }}/{{`{{ imageData.repository }}`}}:{{`{{ imageData.tag || 'latest' }}`}}"
{{- end }}

