
{{ if .Values.matternelle }}
---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: webchat-mattermost-team-edition
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.matternelle.clusterIssuer | default "letsencrypt-prod" }}
    kubernetes.io/ingress.class: {{ .Values.matternelle.ingressClass | default "traefik" }}
spec:
  rules:

  - host: {{.Values.matternelle.domain}}
    http:
      paths:
      - path: /
        backend:
          service:
            name: mattermost
            port:
              number: 8989
        pathType: Prefix
  tls:
    - hosts:
      - {{.Values.matternelle.domain}}
      secretName: {{.Values.matternelle.domain}}
{{ end }}
