apiVersion: v2
name: linuxaid-agents
description: Run the LinuxAid OpenVox agent on KubeAid nodes to manage OS packages, SSH keys and sudo
icon: https://avatars.githubusercontent.com/u/13882947?s=250&v=4
type: application
version: 0.1.0
appVersion: 0.0.1
keywords:
  - obmondo
  - kubeaid
  - linuxaid
  - openvox
