apiVersion: v2
appVersion: 4.18.0
dependencies:
- alias: cnpg
  condition: cnpg.enabled
  name: cluster
  repository: https://cloudnative-pg.github.io/charts
  version: 0.8.1
- alias: mysql
  condition: mysql.enabled
  name: pxc-db
  repository: https://percona.github.io/percona-helm-charts
  version: 1.20.0
description: A Helm chart to deploy coturn
home: https://codeberg.org/open-engineering/coturn-chart
maintainers:
- name: jessebot
  url: https://codeberg.org/jessebot/
name: coturn
sources:
- https://codeberg.org/open-engineering/coturn-chart
- https://github.com/Obmondo/coturn-chart
type: application
version: 10.2.0
