{{- if and .Values.prometheusRule.enabled (hasKey .Values.prometheusRule "velero") ( .Values.prometheusRule.velero.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "backup-exporter.fullname" . }}-velero
  namespace: {{ .Values.prometheusRule.velero.namespace | default "monitoring" }}
  labels:
    {{- include "backup-exporter.labels" . | nindent 4 }}
    {{- if .Values.prometheusRule.velero.labels }}
    {{- toYaml .Values.prometheusRule.velero.labels | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "backup-exporter.name" . }}-velero
      rules:
        - alert: VeleroBackupExporterJobFailed
          expr: max by (type) (backup_exporter_velero_error == 1) > 0
          for: {{ .Values.prometheusRule.velero.alertForDuration | default "5m" }}
          labels:
            severity: {{ .Values.prometheusRule.velero.severity | default "critical" }}
          annotations:
            summary: 'Velero backup exporter job failed'
            description: 'Velero backup exporter error (type: {{ `{{ $labels.type }}` }})'
        - alert: VeleroBackupExceededRPO
          expr: backup_exporter_velero_latest_backup_age > {{ include "backup-exporter.durationToSeconds" .Values.exporter.velero.max_rpo }}
          for: {{ .Values.prometheusRule.velero.alertForDuration | default "5m" }}
          labels:
            severity: {{ .Values.prometheusRule.velero.severity | default "critical" }}
          annotations:
            summary: 'Velero backup exceeded RPO'
            description: 'Backup for {{ `{{ $labels.namespace }}` }}/{{ `{{ $labels.resource_name }}` }} ({{ `{{ $labels.resource_type }}` }}, method: {{ `{{ $labels.backup }}` }}) exceeded RPO (age: {{ `{{ $value }}` }})'
        - alert: VeleroBackupMissing
          expr: backup_exporter_velero_latest_backup_age == 0
          for: {{ .Values.prometheusRule.velero.alertForDuration | default "5m" }}
          labels:
            severity: {{ .Values.prometheusRule.velero.severity | default "critical" }}
          annotations:
            summary: 'Velero backup missing'
            description: 'No backup found for {{ `{{ $labels.namespace }}` }}/{{ `{{ $labels.resource_name }}` }} ({{ `{{ $labels.resource_type }}` }}, method: {{ `{{ $labels.backup }}` }})'
{{- end }}
