{{- if and ((.Values.global).netpol).enabled ((.Values.global).harbor).netpol }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.global.netpol.releaseName | default .Release.Name }}-networkpolicy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: cilium-networkpolicy
spec:
  endpointSelector:
    matchLabels:
      {{- if .Values.global.harbor.endpointSelectorLabels }}
      {{- range $key, $value := .Values.global.harbor.endpointSelectorLabels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- else }}
      app.kubernetes.io/instance: harbor
      {{- end }}
  ingress:
    # Allow same namespace traffic
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace | quote }}
    # traefik -> harbor
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Values.global.netpol.traefik.namespace | default "traefik" | quote }}
            {{- if .Values.global.netpol.traefik.labels }}
            {{- range $key, $value := .Values.global.netpol.traefik.labels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            {{- else }}
            app.kubernetes.io/name: traefik
            {{- end }}
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "5000"
              protocol: TCP
    # harbor <-> harbor (Internal)
    - fromEndpoints:
        - matchLabels:
            {{- if .Values.global.harbor.endpointSelectorLabels }}
            {{- range $key, $value := .Values.global.harbor.endpointSelectorLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            {{- else }}
            app.kubernetes.io/instance: harbor
            {{- end }}
  egress:
    # harbor <-> harbor (Internal)
    - toEndpoints:
        - matchLabels:
            {{- if .Values.global.harbor.endpointSelectorLabels }}
            {{- range $key, $value := .Values.global.harbor.endpointSelectorLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            {{- else }}
            app.kubernetes.io/instance: harbor
            {{- end }}
    # Harbor -> Redis
    - toEndpoints:
        - matchLabels:
            app: harbor-redis
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
    # Harbor -> pgsql
    - toEndpoints:
        - matchLabels:
            cnpg.io/cluster: harbor-pgsql
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    # Harbor -> kube-apiserver
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "6443"
              protocol: TCP
    # Harbor -> DNS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    # FQDNs
    - toFQDNs:
        - matchName: "github.com"
        - matchName: "ghcr.io"
        - matchName: "registry-1.docker.io"
        - matchName: "auth.docker.io"
        - matchName: "production.cloudflare.docker.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
{{- end }}