apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeaid-security-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeaid-security-exporter.labels" . | nindent 4 }}
