apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: argo-cd-{{ .Values.global.clusterName }}
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  repoURL: https://argoproj.github.io/argo-helm
  chartName: argo-cd
  namespace: argo-cd
  releaseName: argo-cd
  options:
    waitForJobs: true
    wait: true
    timeout: 5m0s
    install:
      createNamespace: true
  valuesTemplate: |
    configs:
      repositories:
        kubeaid-repo:
          name: kubeaid
          type: {{ .Values.global.kubeaid.type | default "git" }}
          url: {{ .Values.global.kubeaid.repo }}
