{{- if (.Values.provider).aws }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ccm-aws-{{ .Values.global.clusterName }}
  namespace: capi-cluster-{{ .Values.global.customerid }}
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  repoURL: https://kubernetes.github.io/cloud-provider-aws
  chartName: aws-cloud-controller-manager
  namespace: kube-system
  releaseName: aws-cloud-controller-manager
  version: 0.0.8
  options:
    waitForJobs: true
    wait: true
    timeout: 5m0s
  valuesTemplate: |
    namespace: kube-system
    image:
      tag: v1.30.0
    args:
      - --v=2
      - --cloud-provider=aws
      - --use-service-account-credentials=true
      - --configure-cloud-routes=false
    clusterRoleRules:
      - apiGroups:
        - ""
        resources:
        - events
        verbs:
        - create
        - patch
        - update
      - apiGroups:
        - ""
        resources:
        - nodes
        verbs:
        - '*'
      - apiGroups:
        - ""
        resources:
        - nodes/status
        verbs:
        - patch
      - apiGroups:
        - ""
        resources:
        - services
        verbs:
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - ""
        resources:
        - services/status
        verbs:
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - ""
        resources:
        - serviceaccounts
        verbs:
        - create
        - get
      - apiGroups:
        - ""
        resources:
        - persistentvolumes
        verbs:
        - get
        - list
        - update
        - watch
      - apiGroups:
        - ""
        resources:
        - endpoints
        verbs:
        - create
        - get
        - list
        - watch
        - update
      - apiGroups:
        - coordination.k8s.io
        resources:
        - leases
        verbs:
        - create
        - get
        - list
        - watch
        - update
      - apiGroups:
        - ""
        resources:
        - serviceaccounts/token
        verbs:
        - create
      - apiGroups:
          - authentication.k8s.io
        resources:
          - tokenreviews
        verbs:
          - create
      - apiGroups:
          - authorization.k8s.io
        resources:
          - subjectaccessreviews
        verbs:
          - create
{{- end }}
