{{- if (.Values.provider).hetzner }}
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: hetzner-{{ .Values.global.customerid }}
  namespace: capi-cluster-{{ .Values.global.customerid }}
spec:
  configSecret:
    name: capi-cluster-hetzner
    namespace: capi-cluster-{{ .Values.global.customerid }}
  version: {{ .Values.global.caph.version }}
  fetchConfig:
    url: https://github.com/syself/cluster-api-provider-hetzner/releases/download/{{ .Values.global.caph.version }}/infrastructure-components.yaml
  manager:
    # bug: cluster-api renders it as
    # --metrics-bind-addr and CAPH wants --metrics-bind-address
    # metrics:
    #   bindAddress: ":8181"
    # syncPeriod: 10m0s
{{- end }}
