apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: sealed-secerts-{{ .Values.global.clusterName }}
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  repoURL: https://bitnami-labs.github.io/sealed-secrets
  chartName: sealed-secrets
  namespace: system
  releaseName: sealed-secrets
  options:
    waitForJobs: true
    wait: true
    timeout: 5m0s
    install:
      createNamespace: true
  valuesTemplate: |
    namespace: system
    resources:
      limits:
        memory: 32Mi
      requests:
        cpu: 1m
        memory: 8Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
