---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane
  namespace: capi-cluster-{{ .Values.global.customerid }}
spec:
  template:
    spec:
      hostSelector:
        matchLabels:
          role: {{ .Values.global.clusterName }}-control-plane
      installImage:
        image:
          path: /root/.oldroot/nfs/images/Ubuntu-2204-jammy-amd64-base.tar.gz
        partitions:
        - fileSystem: ext4
          mount: /boot
          size: 1024M
        - fileSystem: vg0
          mount: lvm
          size: 100G
        swraid: 1
        swraidLevel: 1
        logicalVolumeDefinitions:
        - vg: vg0
          name: root
          mount: /
          filesystem: ext4
          size: 20G
        postInstallScript: |
          #!/bin/bash
          # NOTE: it will create problem, if there are 2 interface which are UP
          # but lets handle it later
          interface_name=$(ip link show | grep 'UP mode' | awk '{print $2}' | cut -d ':' -f1 )
          touch /etc/netplan/60-floating-ip.yaml
          chmod 600 /etc/netplan/60-floating-ip.yaml
          cat << EOT > /etc/netplan/60-floating-ip.yaml
          # Floating IP from Hetzner
          network:
            version: 2
            renderer: networkd
            ethernets:
              $interface_name:
                addresses:
                - {{ .Values.controlPlaneEndpoint.host }}/32
          EOT
          mkdir -p /etc/cloud/cloud.cfg.d && touch /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
          echo "network: { config: disabled }" > /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
          apt-get update && apt-get install -y cloud-init apparmor apparmor-utils
          cat << EOT > /etc/cloud/cloud.cfg.d/99-admin-ssh-keys.cfg
          users:
            - name: root
              ssh_authorized_keys:
              {{- range .Values.global.sshKeys }}
               - {{ . }}
              {{- end }}
          EOT
          cloud-init clean --logs
      sshSpec:
        portAfterCloudInit: 22
        portAfterInstallImage: 22
        secretRef:
          key:
            name: sshkey-name
            privateKey: ssh-privatekey
            publicKey: ssh-publickey
          name: capi-cluster-robot-ssh
