{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  {{- if .Values.postgres.recover }}
  name: {{ .Release.Name }}-pgsql-recover
  {{- else }}
  name: {{ .Release.Name }}-pgsql
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.postgres.instance | default 1 }}
  {{- if .Values.postgres.recover }}
  bootstrap:
    recovery: {{ .Release.Name }}-pgsql
  {{- else }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.bootstrap.initdb.database | default "mastodon" }}
      owner: {{ .Values.postgres.bootstrap.initdb.owner | default "mastodon" }}
  {{- end }}
  resources:
    limits:
      memory: {{ .Values.postgres.resources.limits.memory | default "1Gi" }}
      cpu: {{ .Values.postgres.resources.limits.cpu | default "500m" }}
    requests:
      memory: {{ .Values.postgres.resources.requests.memory | default "512Mi" }}
      cpu: {{ .Values.postgres.resources.requests.cpu | default "250m" }}
  storage:
    size: {{ .Values.postgres.size }}
    {{- if .Values.postgres.storageClass }}
    storageClass: {{ .Values.postgres.storageClass }}
    {{- end }}
  {{- if .Values.postgres.recover }}
  externalClusters:
    - name: {{ .Release.Name }}-pgsql
      barmanObjectStore:
        destinationPath: {{ .Values.postgres.backup.destinationPath }}
        endpointURL: {{ .Values.postgres.backup.endpointURL }}
        {{- if eq .Values.postgres.backup.cloud "aws" }}
        s3Credentials:
          accessKeyId:
            name: postgresql-psql-backup-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: postgresql-psql-backup-creds
            key: ACCESS_SECRET_KEY
        {{- end }}
        {{- if eq .Values.postgres.backup.cloud "azure" }}
        azureCredentials:
          connectionString:
            name: postgresql-psql-backup-creds
            key: AZURE_CONNECTION_STRING
          storageAccount:
            name: postgresql-psql-backup-creds
            key: AZURE_STORAGE_ACCOUNT
          storageKey:
            name: postgresql-psql-backup-creds
            key: AZURE_STORAGE_KEY
          storageSasToken:
            name: postgresql-psql-backup-creds
            key: AZURE_STORAGE_SAS_TOKEN
        {{- end }}
        wal:
          maxParallel: 8
  {{- end }}
  {{- if .Values.postgres.backup }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.postgres.backup.destinationPath }}
      endpointURL: {{ .Values.postgres.backup.endpointURL }}
      {{- if eq .Values.postgres.backup.cloud "aws" }}
      s3Credentials:
        accessKeyId:
          name: postgresql-psql-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: postgresql-psql-backup-creds
          key: ACCESS_SECRET_KEY
      {{- end }}
      {{- if eq .Values.postgres.backup.cloud "azure" }}
      azureCredentials:
        connectionString:
          name: postgresql-psql-backup-creds
          key: AZURE_CONNECTION_STRING
        storageAccount:
          name: postgresql-psql-backup-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: postgresql-psql-backup-creds
          key: AZURE_STORAGE_KEY
        storageSasToken:
          name: postgresql-psql-backup-creds
          key: AZURE_STORAGE_SAS_TOKEN
      {{- end }}
      wal:
        compression: gzip
        encryption: AES256
    retentionPolicy: "30d"
  {{- end }}
{{- end }}
