{{- if and .Values.redis.enabled (eq .Values.redis.mode "standalone") }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: {{ .Values.redis.name | default (printf "%s-redis" .Release.Name) }}
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.2.6
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: Always
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.redis.storage | default "2Gi" }}
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
{{- end }}
