{
 "title": "App Suite / DCS",
 "tags": [
  "app-suite",
  "java"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,30m,1h,6h,1d" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(process_uptime_seconds{service=~\".*documents-collaboration.*\"}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(dcs_activemq_health_percent{namespace=\"$namespace\",service=~\".*documents-collaboration.*\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(dcs_activemq_health_percent{namespace=\"$namespace\",service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Experimental",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DCS Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dcs_activemq_up_time_ms{pod=\"$pod\"} ",
       "legendFormat": "{{broker}} {{pod}}"
      }
     ]
    },
    {
     "title": "Metrics to be Displayed",
     "type": "text",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "options": {
      "content": "# Metrics\nJVM Metrics should appear in the corresponding dashboard.\n--\ndcs_activemq_health_percent (x)\ndcs_activemq_up_time_ms (x)\n--\ndcs_activemq__queue_size (x)\ndcs_activemq_blocked_average_time_ms (x)\ndcs_activemq_enqueue_max_time_ms (x)\ndcs_activemq_in_flight_count (x)\n--\nTotal / per Broker\nenqueue_count (x/x)\ndequeue_count (x/x)\n-- \nconnections_count_total (x)\ncurrent_connections_count (x)\nbrokers_count (x)\nconsumer_count_total (x)\nconsumer_count (x)\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
     }
    },
    {
     "title": "Todo",
     "type": "text",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
     "options": {
      "content": "Thresholds / limits haben wir nicht..."
     }
    },
    {
     "title": "DCS Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dcs_activemq_up_time_ms{pod=\"$pod\"} "
      }
     ]
    }
   ]
  },
  { "title": "DCS Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Process Uptime [[service]]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{pod=~\"$pod\"} "
    }
   ]
  },
  {
   "title": "Instant ActiveMQ Health % ($pod) ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dcs_activemq_health_percent{pod=~\"$pod\"}",
     "legendFormat": "{{broker}} {{pod}} "
    }
   ]
  },
  {
   "title": "ActiveMQ Queue Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "enqueue_count_total ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rate(dcs_activemq_enqueue_count_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{broker}} {{pod}}"
      }
     ]
    },
    {
     "title": "dequeue_count_total ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 7 },
     "targets": [
      {
       "expr": "rate(dcs_activemq_dequeue_count_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{broker}} {{pod}}"
      }
     ]
    },
    {
     "title": "enqueue_count ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "dcs_activemq_enqueue_count{pod=~\"$pod\"}",
       "legendFormat": "{{broker}} {{pod}}"
      }
     ]
    },
    {
     "title": "dequeue_count ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 16 },
     "targets": [
      {
       "expr": "dcs_activemq_dequeue_count{pod=~\"$pod\"}",
       "legendFormat": "{{broker}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ActiveMQ Queue Timing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "in_flight_count ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "dcs_activemq_in_flight_count{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "queue_size ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "dcs_activemq__queue_size {pod=\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "enqueue_max_time ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dcs_activemq_enqueue_max_time_ms{pod=\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "blocked_average_time ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dcs_activemq_blocked_average_time_ms{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ActiveMQ Connections and Broker / Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "dcs_activemq_brokers_count{pod=~\"$pod\"}",
       "legendFormat": "{{broker}} {{pod}}"
      }
     ]
    },
    {
     "title": "Consumer ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 9 },
     "targets": [
      {
       "expr": "dcs_activemq_consumer_count{pod=~\"$pod\"}",
       "legendFormat": "{{broker}} {{pod}}  Total"
      },
      {
       "expr": "dcs_activemq_consumer_count_total{pod=~\"$pod\"}",
       "legendFormat": "{{broker}} {{pod}} Current"
      }
     ]
    },
    {
     "title": "dcs_activemq_connections ([[pod]])",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "dcs_activemq_connections_count_total{pod=~\"$pod\"}",
       "legendFormat": "{{broker}} {{pod}}  Total"
      },
      {
       "expr": "dcs_activemq_current_connections_count{pod=~\"$pod\"}",
       "legendFormat": "{{broker}} {{pod}} Current"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "DCS Management http requests ($pod)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{pod=~\"$pod\"}[$interval]) ",
       "legendFormat": "{{pod}} {{status}} {{uri}} "
      }
     ]
    },
    {
     "title": "JVM Live Threads ($pod)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{pod=~\"$pod\"}",
       "legendFormat": "{{job}} {{instance}}"
      }
     ]
    },
    {
     "title": "jetty messages ($pod)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(jetty_connections_messages_out_messages_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "out {{pod}}"
      },
      {
       "expr": "rate(jetty_connections_messages_in_messages_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "in {{pod}}"
      }
     ]
    },
    {
     "title": "jetty connections ($pod)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jetty_connections_current_connections{pod=~\"$pod\"}",
       "legendFormat": "current {{pod}}"
      },
      {
       "expr": "jetty_connections_max_connections{pod=~\"$pod\"}",
       "legendFormat": "max {{pod}}"
      }
     ]
    },
    {
     "title": "Logback Events for Service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "logback_events_total{service=~\"$service\"}",
       "legendFormat": " {{pod}} {{level}}"
      }
     ]
    }
   ]
  }
 ]
}