{
 "title": "App Suite / Documents",
 "tags": [
  "java",
  "app-suite"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,30m,1h,6h,1d" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(appsuite_documents_median_size_total{service=~\".*core-mw-monitoring\"}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(appsuite_documents_median_size_total{namespace=\"$namespace\",service=~\".*core-mw-monitoring\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(appsuite_documents_median_size_total{namespace=\"$namespace\",service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MW Uptime / Memory ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "uptime JVM ($pod)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "process_uptime_seconds{pod=~\"$pod\"}",
       "legendFormat": "uptime {{service}} {{pod}}"
      }
     ]
    },
    {
     "title": "Heap Memory [[pod]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=~\"$pod\", area=\"heap\"})",
       "legendFormat": "Used {{pod}}"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod=~\"$pod\", area=\"heap\"})",
       "legendFormat": "Committed {{pod}}"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod=~\"$pod\", area=\"heap\"})",
       "legendFormat": "Max {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running MWs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(appsuite_documents_median_size_total{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Open Docs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appsuite_documents_docprocessor_count{pod=~\"$pod\"}",
     "legendFormat": "DocProcessorCount"
    }
   ]
  },
  {
   "title": "DocCreate / [[interval]]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(appsuite_documents_created_count_total{pod=~\"$pod\"}[$interval]))",
     "legendFormat": "DocCreation"
    }
   ]
  },
  {
   "title": "DocOpen / [[interval]]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(appsuite_documents_opened_count_text_total{pod=~\"$pod\"}[$interval])+increase(appsuite_documents_opened_count_spreadsheet_total{pod=~\"$pod\"}[$interval])+increase(appsuite_documents_opened_count_presentation_total{pod=~\"$pod\"}[$interval]))",
     "legendFormat": "L-Active Sessions"
    }
   ]
  },
  {
   "title": "DocClose / [[interval]]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(appsuite_documents_closed_count_text{pod=~\"$pod\",type=\"total\"}[$interval])+increase(appsuite_documents_closed_count_spreadsheet{pod=~\"$pod\",type=\"total\"}[$interval])+increase(appsuite_documents_closed_count_presentation{pod=~\"$pod\",type=\"total\"}[$interval]))",
     "legendFormat": "L-Active Sessions"
    }
   ]
  },
  {
   "title": "Save / [[interval]]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(appsuite_documents_saved_count_text_total{pod=~\"$pod\"}[$interval]))+max(increase(appsuite_documents_saved_count_spreadsheet_total{pod=~\"$pod\"}[$interval]))+max(increase(appsuite_documents_saved_count_presentation_total{pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Save"
    }
   ]
  },
  {
   "title": "FSS AvgSaveTime / Doc",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(appsuite_documents_background_save_average_time_ms)"
    }
   ]
  },
  {
   "title": "Documents ($pod)",
   "type": "graph",
   "description": "DocProxies Count and Rates for Creation/Close per Minute and Operations per Second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(appsuite_documents_created_count_total{pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Creation"
    },
    {
     "expr": "sum(increase(appsuite_documents_closed_count_text{pod=~\"$pod\",type=\"total\"}[$interval])+increase(appsuite_documents_closed_count_spreadsheet{pod=~\"$pod\",type=\"total\"}[$interval])+increase(appsuite_documents_closed_count_presentation{pod=~\"$pod\",type=\"total\"}[$interval]))",
     "legendFormat": "Close"
    },
    {
     "expr": "sum(rate(appsuite_documents_operations_count_text{type=\"incoming\",pod=~\"$pod\"}[$interval]))+sum(rate(appsuite_documents_operations_count_spreadsheet{type=\"incoming\",pod=~\"$pod\"}[$interval]))+sum(rate(appsuite_documents_operations_count_presentation{type=\"incoming\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Operations"
    },
    {
     "expr": "sum(increase(appsuite_documents_opened_count_text_total{pod=~\"$pod\"}[$interval])+increase(appsuite_documents_opened_count_spreadsheet_total{pod=~\"$pod\"}[$interval])+increase(appsuite_documents_opened_count_presentation_total{pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Opened {{pod}}"
    }
   ]
  },
  {
   "title": "Documents Save (per type stacked) / $interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(appsuite_documents_saved_count_text_total{pod=~\"$pod\"}[$interval])",
     "legendFormat": "TextSave {{pod}}"
    },
    {
     "expr": "increase(appsuite_documents_saved_count_spreadsheet_total{pod=~\"$pod\"}[$interval])",
     "legendFormat": "SpreadsheetSave {{pod}}"
    },
    {
     "expr": "increase(appsuite_documents_saved_count_presentation_total{pod=~\"$pod\"}[$interval])",
     "legendFormat": "PresentationSave {{pod}}"
    },
    { "legendFormat": "FSS" }
   ]
  },
  {
   "title": "Documents Details Open/Close/Create + Save ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DocsCreated / DocsClosed / DocsOpened per type / $interval  ([[pod]])",
     "type": "graph",
     "description": "Increase per 1 minute",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(appsuite_documents_created_count{pod=~\"$pod\"}[1m])",
       "legendFormat": "Created{{type}} {{pod}}"
      },
      {
       "expr": "increase(appsuite_documents_opened_count_text_total{format=\"total\",pod=~\"$pod\"}[1m])",
       "legendFormat": "OpenedText {{pod}}"
      },
      {
       "expr": "increase(appsuite_documents_opened_count_spreadsheet_total{format=\"total\",pod=~\"$pod\"}[1m])",
       "legendFormat": "Opened Spreadsheet {{pod}}"
      },
      {
       "expr": "increase(appsuite_documents_opened_count_presentation_total{format=\"total\",pod=~\"$pod\"}[1m])",
       "legendFormat": "OpenedPresentation {{pod}}"
      },
      {
       "expr": "increase(appsuite_documents_closed_count_text{type=\"total\",pod=~\"$pod\"}[1m])",
       "legendFormat": "ClosedText {{pod}}"
      },
      {
       "expr": "increase(appsuite_documents_closed_count_spreadsheet{type=\"total\",pod=~\"$pod\"}[1m])",
       "legendFormat": "ClosedSpreadsheet {{pod}}"
      },
      {
       "expr": "increase(appsuite_documents_closed_count_presentation{type=\"total\",pod=~\"$pod\"}[1m])",
       "legendFormat": "ClosedPresentation {{pod}}"
      }
     ]
    },
    {
     "title": "Save / $interval by type ([[pod]])",
     "type": "graph",
     "description": "number of documents saves per interval split by document type",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(appsuite_documents_saved_count_text_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "TextSave {{pod}}"
      },
      {
       "expr": "increase(appsuite_documents_saved_count_spreadsheet_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "SpreadsheetSave {{pod}}"
      },
      {
       "expr": "increase(appsuite_documents_saved_count_presentation_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "PresentationSave {{pod}}"
      },
      { "legendFormat": "FSS" }
     ]
    },
    {
     "title": "Save Triggers / $interval ([[pod]] )",
     "type": "graph",
     "description": "Trigger for Document Saves per $interval",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(appsuite_documents_saved_count_text{pod=~\"$pod\"}[1m])",
       "legendFormat": "Text {{type}} {{pod}}"
      },
      {
       "expr": "increase(appsuite_documents_saved_count_spreadsheet{pod=~\"$pod\"}[1m])",
       "legendFormat": "Spreadsheet {{type}} {{pod}}"
      },
      {
       "expr": "increase(appsuite_documents_saved_count_presentation{pod=~\"$pod\"}[1m])",
       "legendFormat": "Presentation {{type}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations and OT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Operations In and Out ([[pod]])",
     "type": "graph",
     "description": "increase per 1 minute",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(appsuite_documents_operations_count_text{pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}} Text {{type}}"
      },
      {
       "expr": "rate(appsuite_documents_operations_count_presentation{pod=~\"$pod\"}[$interval])",
       "legendFormat": "$pod Pres {{type}}"
      },
      {
       "expr": "rate(appsuite_documents_operations_count_spreadsheet{pod=~\"$pod\"}[$interval])",
       "legendFormat": "$pod Spread {{type}}"
      }
     ]
    },
    {
     "title": "OT (T/$interval) by Type  ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 11, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(appsuite_documents_operations_transformed_count{pod=~\"$pod\"}[$interval])",
       "legendFormat": "$pod ServerOT {{type}}"
      },
      {
       "expr": "delta(appsuite_documents_operations_transformed_count_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}} ServerOT Total "
      },
      {
       "expr": "delta(appsuite_documents_operations_unresolvable_count_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "{{pod}} Unresolved Total "
      }
     ]
    },
    {
     "title": "Operations Ratio out/in ([[pod]])",
     "type": "graph",
     "description": "Collaboration ratio; ratio of operations distributed to operations incoming per document type, namespace and pod",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,pod) (increase(appsuite_documents_operations_count_presentation{type=\"distributed\",pod=~\"$pod\"}[1m])) / sum by (namespace,pod) (increase(appsuite_documents_operations_count_presentation{type=\"incoming\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "Presentation-CollabRatio {{pod}} {{type}}"
      },
      {
       "expr": "sum by (namespace,pod) (increase(appsuite_documents_operations_count_text{type=\"distributed\",pod=~\"$pod\"}[1m])) / sum by (namespace,pod) (increase(appsuite_documents_operations_count_text{type=\"incoming\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "Text-CollabRatio {{pod}}"
      },
      {
       "expr": "sum by (namespace,pod) (increase(appsuite_documents_operations_count_spreadsheet{type=\"distributed\",pod=~\"$pod\"}[1m])) / sum by (namespace,pod) (increase(appsuite_documents_operations_count_spreadsheet{type=\"incoming\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "Spread-CollabRatio {{pod}}"
      }
     ]
    },
    {
     "title": "Server OT  ([[pod]]) transformed / unresolvable / reloads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(appsuite_documents_operations_transformed_count_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "Transformed {{pod}}"
      },
      {
       "expr": "rate(appsuite_documents_operations_unresolvable_count_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "Unresolvable {{pod}}"
      },
      {
       "expr": "rate(appsuite_documents_operations_unresolvable_reload_count_total{pod=~\"$pod\"}[$interval])",
       "legendFormat": "Reloads [[pod]]"
      }
     ]
    }
   ]
  },
  {
   "title": "Background Save ([[pod]])",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "AvgTime of DocSave - Max over [[interval]] ([[pod]])",
     "type": "graph",
     "description": "Maximum of Average Duration for Document Background Saves during interval $interval; If  no documents are saved the value is zero.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max_over_time(appsuite_documents_background_save_average_time_ms{pod=~\"$pod\"}[$interval])",
       "legendFormat": "MaxOverTime AvgTime {{pod}}"
      }
     ]
    },
    {
     "title": "Cycle Duration and DocsSaved Count - Max over $interval ([[pod]])",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ms", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "max_over_time(appsuite_documents_background_save_time_ms{pod=~\"$pod\"}[$interval])",
       "legendFormat": "Save Time Max over pods "
      },
      {
       "expr": "max_over_time(appsuite_documents_background_save_count{pod=~\"$pod\"}[$interval])",
       "legendFormat": "Save Count {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}