name: Lint Markdown

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'

permissions:
  contents: read

# This will only allow a single markdownlint action to run per PR.
# Any github action running on the older commits will be aborted.
concurrency:
  group: markdownlint-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 1
          # Sparse checkout will only pull the specified files instead of the entire repo
          # This saves around 4s per run.
          # Sparse checkout sometimes pulls all files
          # https://github.com/actions/checkout/issues/1550

          # Add a new step to test sparse-checkout if it fails as mentioned in the above issue
          # - name: Temp
          #   working-directory: .
          #   run: ls -la .server
          #   shell: bash

          sparse-checkout: |
            **/*.md
            .markdownlint-cli2.yaml
          sparse-checkout-cone-mode: false

      - name: Run markdownlint
        uses: docker://davidanson/markdownlint-cli2:v0.23.0@sha256:97996d59837fa7cc27fc5f0e16d72eae71d0cefee15c437ee1d7cdbccb5552be
        with:
          entrypoint: markdownlint-cli2
          args: '"**/*.md" --config .markdownlint-cli2.yaml'
