name: markdownlint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'

permissions:
  contents: read

concurrency:
  group: markdownlint-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run markdownlint
        uses: docker://davidanson/markdownlint-cli2:v0.23.0
        with:
          entrypoint: markdownlint-cli2
          args: '"**/*.md" --config .markdownlint-cli2.yaml'