name: markdownlint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'

permissions:
  contents: read

concurrency:
  group: markdownlint-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          sparse-checkout: |
            **/*.md
            .markdownlint-cli2.yaml
          sparse-checkout-cone-mode: false

      - name: Temp
        working-directory: .
        run: ls -alh .
        shell: bash

      - name: Run markdownlint
        uses: docker://davidanson/markdownlint-cli2:v0.23.0@sha256:97996d59837fa7cc27fc5f0e16d72eae71d0cefee15c437ee1d7cdbccb5552be
        with:
          entrypoint: markdownlint-cli2
          args: '"**/*.md" --config .markdownlint-cli2.yaml'
