name: Test OPA Policies

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'argocd-helm-charts/gatekeeper/policies/**'

permissions:
  contents: read

# This will only allow a single markdownlint action to run per PR.
# Any github action running on the older commits will be aborted.
concurrency:
  group: test-opa-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-opa:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2.2.0
        with:
          version: "1.6.0"
          static: true

      - name: Run OPA tests
        run: opa test ./argocd-helm-charts/gatekeeper/policies -v
