---
name: goreleaser

"on":
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write
  pull-requests: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          # This is required for the changelog to work correctly.
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7.0.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7.2.3
        with:
          version: "v2.12.7"
          args: release --clean --config .goreleaser-github.yaml --release-notes=.release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Helm
        uses: azure/setup-helm@v5
        with:
          version: 'v3.21.3'

      - name: Log in to GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_USER: ${{ github.actor }}
        run: |
          echo "$GHCR_TOKEN" \
            | helm registry login ghcr.io -u "$GHCR_USER" --password-stdin

      - name: Publish charts listed in .helm-charts-publish
        env:
          HELM_OCI_REGISTRY: oci://ghcr.io/obmondo/charts
        run: ./bin/publish-helm-chart.sh
